# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Город')),
                ('latitude', models.FloatField(verbose_name='Ширина')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обноления')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.FloatField(verbose_name='Максимум')),
                ('min', models.FloatField(verbose_name='Минимум')),
                ('day', models.FloatField(verbose_name='Днем')),
                ('night', models.FloatField(verbose_name='Ночью')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('wind', models.FloatField(verbose_name='Ветер')),
                ('clouds', models.IntegerField(verbose_name='Облачность')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('status', models.CharField(max_length=60, verbose_name='Описание')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='openweathermap.City')),
            ],
        ),
        migrations.AddField(
            model_name='temperature',
            name='weather',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openweathermap.Weather'),
        ),
    ]
